def print_quote_summary(client_name, items_list, subtotal, discount, shipping, total):
    print("\n" + "=" * 45)
    print(" RESUMEN DE LA COTIZACIÓN ".center(45, "="))
    print("=" * 45)
    print(f" Cliente: {client_name}")
    print("-" * 45)
    print(" Productos:")
    for item in items_list:
        print(f"  * {item}")
    print("-" * 45)
    print(f" Subtotal: C${subtotal:.2f}")
    print(f" Descuento aplicado: -C${discount:.2f}")
    print(f" Costo de envío: +C${shipping:.2f}")
    print("-" * 45)
    print(f" TOTAL A PAGAR: C${total:.2f}")
    print("=" * 45 + "\n")