def mostrar_resumen_cotizacion(cliente, producto, cantidad, precio, subtotal, descuento, envio, total):
    """Genera el reporte impreso final de la cotización."""
    print("\n" + "=" * 50)
    print(" RESUMEN DE LA COTIZACIÓN ".center(50, "="))
    print("=" * 50)
    print(f" Cliente: {cliente}")
    print(f" Producto: {producto}")
    print(f" Cantidad: {cantidad}")
    print(f" Precio unitario: ${precio:.2f}")
    print("-" * 50)
    print(f" Subtotal: ${subtotal:.2f}")
    print(f" Descuento aplicado: -${descuento:.2f}")
    print(f" Costo de envío: +${envio:.2f}")
    print("-" * 50)
    print(f" TOTAL A PAGAR: ${total:.2f}")
    print("=" * 50 + "\n")